packages:
  - packages/*
  - apps/*
  - libraries/*
  - services/*

catalogs:
  biome:
    "@biomejs/biome": 1.8.3

  effect:
    effect: 3.5.8
    "@effect/platform": ^0.60.2
    "@effect/platform-browser": ^0.39.2
    "@effect/vitest": ^0.6.12

  typescript:
    typescript: 5.5.4
    "@types/node": ^22.0.0

  vite:
    vite: 5.3.5
    vitest: 2.0.4
    vite-plugin-dts: ~3.9.1

  attw:
    "@arethetypeswrong/cli": ^0.15.3

  api-extractor:
    "@microsoft/api-extractor": ^7.47.4
    "@microsoft/api-documenter": ^7.25.9
