import { useState, useEffect } from "react";

import "./SidePanel.css";

export const SidePanel = () => {
	const [countSync, setCountSync] = useState(0);
	const link = "https://github.com/guocaoyi/create-chrome-ext";

	return (
		<main>
			<h3>SidePanel Page</h3>
			<h4>Count from Popup: {countSync}</h4>
			<a href={link} target="_blank">
				generated by create-chrome-ext
			</a>
		</main>
	);
};

export default SidePanel;
