name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - name: Install dependencies
      run: pnpm install

    - name: Build packages
      run: pnpm build

    - name: Unit Test Packages
      run: pnpm test

    # setup node for verdaccio now
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: http://localhost:4873
        cache: pnpm

    - name: publish to verdaccio
      uses: ./.github/actions/verdaccio-publish
      env:
        PR_NUMBER: ${{ github.event.number }}
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
